@startuml show_pixel_frame
title method : show()
skinparam style strictuml
skinparam SequenceMessageAlignment center
[-> GraphicWidget ++ : show()
GraphicWidget -> graphic_display_screen ++: show(pixel_frame, anchor_x, anchor_y)
return Done
[<- GraphicWidget :done
@enduml

@startuml draw_border
title method : draw_border(color)
skinparam style strictuml
skinparam SequenceMessageAlignment center
[-> GraphicWidget : draw_border(color)
alt widget_with_border == true
GraphicWidget -> GraphicFramebuffer ++: rect(x,y,width,height)
GraphicFramebuffer -> graphic_display_screen ++: pixel()
return 
return
end
[<-- GraphicWidget
@enduml

@startuml draw
title method : draw
skinparam style strictuml
skinparam SequenceMessageAlignment center
ref over implemented_widget : get_value_of_interest()
ref over implemented_widget : effective widget drawing
ref over implemented_widget : draw_border(color)
ref over implemented_widget : show()
@enduml

@startuml draw_if_changed
' header HEADER
' footer Page %page% of %lastpage%
title scenario : draw_if_changed
skinparam style strictuml
skinparam SequenceMessageAlignment center

loop while(true)
model -> implemented_widget ++: draw_refresh()
alt model_has_changed
ref over implemented_widget : draw()
implemented_widget->model ++: clear_change_flag()
return Done
return Done
end
end
@enduml