@startuml show_pixel_frame
title method : show_pixel_frame
skinparam style strictuml
skinparam SequenceMessageAlignment center
widget -> widget : show()
activate widget
widget -> display_screen : show(pixel_frame, anchor_x, anchor_y)
activate display_screen
return Done
@enduml


@startuml draw_if_changed
' header HEADER
' footer Page %page% of %lastpage%
title scenario : draw_if_changed
skinparam style strictuml
skinparam SequenceMessageAlignment center

loop while(true)
model -> widget : draw_refresh()
activate  widget
alt model_has_changed
widget -> model : get_values_of_interest()
activate widget
activate model
model --> widget : values
deactivate model
deactivate widget
widget -> widget : draw()
activate widget
widget -> framebuffer : graphic_primitives()
activate framebuffer
return Done
deactivate widget
widget -> widget : draw_border()
activate widget
widget -> framebuffer : rec()
activate framebuffer
return Done
return Done
ref over widget,display_screen :  show_pixel_frame

return Done
end
end
@enduml